apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-app
  namespace: dependency-track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dependency-track-application
  template:
    metadata:
      labels:
        app: dependency-track-application
    spec:
      containers:
        - name: dependency-ui
          image: dependencytrack/frontend:4-snapshot
          ports: 
            - containerPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-backend
  namespace: dependency-track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dependency-track-apiserver
  template:
    metadata:
      labels:
        app: dependency-track-apiserver
    spec:
      containers:
        - name: dependency-apiserver
          image: dependencytrack/apiserver:5-snapshot
          ports: 
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: dependency-track-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dependency-track-postgres
  namespace: dependency-track
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dependency-track-pgsql
  template:
    metadata:
      labels:
        app: dependency-track-pgsql
    spec:
      containers:
        - name: dependency-postgresql
          image: postgres:18-alpine
          envFrom:
            - configMapRef:
                name: dependency-track-configmap