apiVersion: v1
kind: Service
metadata:
  name: dependency-track-service
  namespace: dependency-track
spec:
  type: ClusterIP
  selector:
    app: dependency-track-application
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dependency-track-apiservice
  namespace: dependency-track
spec:
  type: ClusterIP
  selector:
    app: dependency-track-apiserver
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dependency-track-postgresql
  namespace: dependency-track
spec:
  type: ClusterIP
  selector:
    app: dependency-track-pgsql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432