apiVersion: v1
kind: ConfigMap
metadata:
  name: dependency-track-configmap
  namespace: dependency-track
data:
  DT_DATASOURCE_URL: "jdbc:postgresql://dependency-track-postgresql:5432/dtrack"
  DT_DATASOURCE_USERNAME: "dtrack"
  DT_DATASOURCE_PASSWORD: "dtrack"
  POSTGRES_DB: "dtrack"
  POSTGRES_USER: "dtrack"
  POSTGRES_PASSWORD: "dtrack"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  API_BASE_URL: "http://localhost:8085"